### ISSUE TITLE
Unable to set SSH port

### ISSUE THREAD

**Issue by obaqueiro** [cespare/weave#8]
Right now, it seems that it's not possible to set the connection port number to other than the default (22).

**Comment by cespare** [comment]
Yeah, that's true. I'll make an way to pass in custom options to `Net::SSH`.

Side note: running SSH on a non-standard port "for security" is not a good practice.

**Comment by cespare** [comment]
Actually, this is possible today. `Net::SSH` uses your regular ssh configuration including `~/.ssh/config`. So whatever configuration is specified in there is picked up. Example:

```
# ~/.ssh/config
Host example.com
  Port 1234
```

``` ruby
Weave.connect(["user@example.com"]) { run "ls" }
```

**Comment by cespare** [comment]
I've made a change in 84a87305936935d4ed6cf7a4d905d1228e4da976 to allow for passing arbitrary `Net::SSH` options through. So for instance, you can now do

``` ruby
Weave.connect(["user@example.com"], :net_ssh_options => { :port => 1234 }) do
  run "ls"
end
```

**Comment by cespare** [comment]
BTW I put a new version with this change on rubygems as `1.1.0-beta1`.

**Comment by obaqueiro** [comment]
Cool, thanks for this. Actually, The SSH port issue I got was while using Fezzik (which uses weave). The reason for the non-standard connection was mainly to use it with Vagrant, which forwards SSH to some localhost port.  I guess using a combination of .ssh/config  and modifying /etc/hosts  to bind 127.0.0.1 to something like vagrantmachine.local   would also work :)
